apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-wo53
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-wo53
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-wo53
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-wo53
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-wo53
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qhnp-tenant/rhtap-demo-app/hacbs-test-project-wo53@sha256:9babcafd12b00b60c2845501c3b7ee2fee5e1a95a258fe5974bb5933254e5139
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
