apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-wo53
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qhnp-tenant/rhtap-demo-app/hacbs-test-project-wo53@sha256:9babcafd12b00b60c2845501c3b7ee2fee5e1a95a258fe5974bb5933254e5139
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
